//
//  findTheDifference-389.swift
//  Code challenge
//
//  Created by Dave, Hiteshkumar on 7/17/25.
/*
 https://leetcode.com/problems/find-the-difference/description/?envType=problem-list-v2&envId=hash-table
 
 You are given two strings s and t.

 String t is generated by random shuffling string s and then add one more letter at a random position.

 Return the letter that was added to t.

  

 Example 1:

 Input: s = "abcd", t = "abcde"
 Output: "e"
 Explanation: 'e' is the letter that was added.
 Example 2:

 Input: s = "", t = "y"
 Output: "y"
  

 Constraints:

 0 <= s.length <= 1000
 t.length == s.length + 1
 s and t consist of lowercase English letters.
 */

func findTheDifference(_ s: String, _ t: String) -> Character {
    let characters = Array(s)
    var difference = 0
    for char in t {
        difference += Int(char.asciiValue!)
    }
    for char in s {
        difference -= Int(char.asciiValue!)
    }
    return Character(UnicodeScalar(difference)!)
}
